version: 0.0
os: linux
files:
  - source: /
    destination: /apps/vc-chat
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/after_install
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
runas: root
