version: 0.0
os: linux
files:
  - source: /
    destination: /apps/vc-chat
hooks:
  ApplicationStop:
    - location: deploy/stop_server
      timeout: 300
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
  AfterInstall:
    - location: deploy/after_install
      timeout: 300
runas: ec2-user
