version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user/node
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: deploy/install.sh
      timeout: 300
  AfterInstall:
    - location: deploy/post_install.sh
      timeout: 300
  ApplicationStart:
    - location: deploy/run.sh
      timeout: 300
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: validate.sh
      timeout: 300
runas: ec2-user
runas: ec2-user
