#!/bin/sh

set -e

cd /apps/vc-chat

node_version=$(cat .nvmrc)


. ~/.nvm/nvm.sh

if [[ $(nvm ls | grep ${node_version}) == "" ]]; then
  nvm install
else
  nvm use
fi

echo "Installing pm2"
sudo npm install -g pm2

echo "Installing node packages"
npm install

# pm2 start npm -- start