#!/bin/sh
cd /apps/vc-chat

node_version=$(cat .nvmrc)

. ~/.nvm/nvm.sh

if [[ $(nvm ls | grep ${node_version}) == "" ]]; then
  nvm install
else
  nvm use
fi

echo "Installing node packages"
npm install
npm start